

name: Java Maven Build & Publish Artifact

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'corretto'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Generate Report
      run: mvn surefire-report:report 
    - name: List files CompilerMZ
      run: ls -r /home/runner/work/CompilerMZ/CompilerMZ/target/surefire-reports/
    - name: Test and Report
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Maven Tests
        path: /home/runner/work/CompilerMZ/CompilerMZ/target/surefire-reports/
        reporter: java-junit
      continue-on-error: false
   
  publish-job:
    runs-on: ubuntu-latest
    needs: build_test
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'corretto'
    - run: mvn --batch-mode --update-snapshots verify
    - run: mkdir staging && cp target/*.jar staging
    - uses: actions/upload-artifact@v4
      with:
        name: Package
        path: staging
